# Generated by Django 4.0.4 on 2022-05-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(max_length=8)),
                ('expiration_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('date_used', models.DateTimeField()),
                ('special_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offer', to='vouchers.specialoffer')),
            ],
        ),
    ]
