# Generated by Django 4.0.4 on 2022-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_vouchercode_date_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchercode',
            name='date_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
